version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: coredocu-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - ./db/mongodb_data:/data/db

  mongo-express:
    image: mongo-express:1.0.2
    container_name: coredocu-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongodb


  # API .NET 8
  api:
    container_name: coredocu-api
    build:
      context: ./back/CoreDocu.Api
      dockerfile: Dockerfile
    ports:
      - "8091:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
    volumes:
      - ./storage/attachments:/data/core-docu/attachments
    depends_on:
      - mongodb

  # Angular + Nginx
  web:
    container_name: coredocu-web
    build:
      context: ./front/web
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - api
      
volumes:
  mongodb_data:
